### ISSUE TITLE
the running environment 

### ISSUE THREAD

**Issue by JRN1** [plofgren/bidirectional-random-walk#9]
What project is this? SBT project?? What is the running environment of its code??

**Comment by plofgren** [comment]
Right, sbt. You'll notice in the readme it refers to `sbt console` in the example commands. I've run it (or at least related code) on OS X and Linux.

**Comment by JRN1** [comment]
谢谢您的答复，我在Linux上按照readme简单运行了它，我想知道的是代码编译环境，我构造编译环境好像总是有些问题，您可以和我私聊嘛？？非常感谢

**Comment by JRN1** [comment]
Thank you for your reply, I run it simply on the Linux according to readme. I want to know the code compilation environment. It seems that I always have some problems to build the compiler environment. I can ask you for a moment, and will you be convenient to talk to me? Thank you very much.

**Comment by JRN1** [comment]
different
